#pragma once

#define SKILL_ICON(aSkillId) ((1 << 8) + (aSkillId))
#define MASTERY_ICON(aSkillId) ((2 << 8) + (aSkillId))
#define COMBAT_ART_ICON(aSkillId) ((3 << 8) + (aSkillId))

enum{
	MASTERY_ICON_SWORD = 0,
	MASTERY_ICON_LANCE,
	MASTERY_ICON_AXE,
	MASTERY_ICON_BOW,
	MASTERY_ICON_BRAWL,
	MASTERY_ICON_REASON,
	MASTERY_ICON_FAITH,
	MASTERY_ICON_AUTH,
	MASTERY_ICON_RIDE,
	MASTERY_ICON_FLY,
	MASTERY_ICON_HEAVY,
	
	MASTERY_ICON_MAX,
	MASTERY_ICON_NULL = 0xFF,
};